src/components/learn/SelectBox.tsx, src/pages/learn/index.tsx
- close #16 
- useRef를 사용해 구현했습니다.
https://user-images.githubusercontent.com/58380158/179008187-7ab6491e-018f-41a2-a153-75ba97ae77e2.mp4
=> [learn] 셀렉트박스 외부 영역 클릭 시 처리

src/components/landing/Nav.tsx
- close #36 
모달을 <StNav>밖으로 빼야함!
=> [landing] 로그인 모달 

src/components/learnDetail/ConfirmModal.tsx, src/pages/learn/[id].tsx
- close #61
- 코드 리뷰 반영으로 텍스트를 props로 관리하도록 변경하였습니다!
=> [learn_detail] confirm창 컴포넌트 리팩토링

src/components/common/ProfileModal.tsx, src/pages/auth/kakao.tsx, src/pages/learn/[id].tsx
- close #75
학습 상세 페이지에서 띄어쓰기/하이라이트 버튼 눌렀을 때
네비게이션 바 ‘복습하기’ 버튼 눌렀을 때
로그인이 되어 있지 않은 사용자의 경우 로그인 모달을 띄워줍니다.
=> [common] 로그인 필요한 기능 접근 시 로그인 모달 띄우기

src/components/learnDetail/ScriptEdit.tsx, src/pages/learn/[id].tsx, src/services/mock/learn-detail.data.ts
=> [learn_datail] 스크립트버튼 비활성화

src/components/common/NewsList.tsx, src/components/learnDetail/ScriptEdit.tsx, src/components/learnDetail/VideoDetail.tsx, src/pages/learn/[id].tsx, src/pages/review.tsx
- close #88 
- [id].tsx가 복잡해서 VideoDetail 컴포넌트를 하나 생성하고 분리했습니다.
- 뉴스 영상의 endTime이 14.37과 같이 소수 형태인 경우, 반복 재생이 안 되는 이슈가 있었습니다.
[Math.ceil](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Math/ceil)을 통해 integer로 만들어 해결했습니다.
- 스크립트 하이라이트 시 생기는 파란 영역(아래 이미지 참고)은 `::selection`을 통해 제거했습니다. [참고](https://tren-d.tistory.com/entry/%ED%85%8D%EC%8A%A4%ED%8A%B8-%EB%A7%88%EC%9A%B0%EC%8A%A4-%EB%93%9C%EB%9E%98%EA%B7%B8%EC%8B%9C-%EC%83%89%EC%83%81-%EB%B3%80%EA%B2%BD%EB%B0%A9%EB%B2%95-selection)
- 로그인 안 된 상태로 즐겨찾기 버튼 눌렀을 때
https://user-images.githubusercontent.com/58380158/181510377-9af6176e-d0a5-4f95-bd12-09ecd2c86207.mp4
- 하이라이트
https://user-images.githubusercontent.com/58380158/181510050-853eaf39-0b7a-4d0a-a106-9847047f8dac.mp4
=> [common] 여러 페이지 리팩터링

src/components/common/NavigationBar.tsx, src/components/learnDetail/ScriptEdit.tsx
- close #87
- 아주 자잘자잘한 필요없는 코드를 삭제하고 정리했습니다. 
- 원래 중복 asset인줄 알았던 마이크가 다른 마이크였네요~^^..
=> [common] 불필요한 코드 정리

src/components/landing/ScrollControl.tsx, src/components/landing/SliderContainer.tsx, src/components/landing/useSlideObserver.ts, src/pages/index.tsx
- close #89 
- 슬라이더 버튼 누르면 옵저버 0.5초간 끄도록 설정해서 구현했어요!
- 나중에 시간이 남으면 그때 scroll 계산하는걸로 리팩갈길게욤욤
=> [landing] smooth 속성 추가

src/components/common/Footer.tsx
- close #128 
- 19일(월) 오프라인 회의 때 기획 분들과 디자이너 분들에게 제안/질문 드릴 게 있어서 답변 듣고 merge하도록 하겠습니다!
ㄴ질문 완료! 코드가 달라지는 점은 없어서 리뷰 진행해주시면 됩니다. 
https://user-images.githubusercontent.com/63948884/190912625-3344e4a4-ae47-4350-b322-2f60bae4477a.mp4
=> [common] 푸터 반응형 구현

src/pages/learn/[id].tsx, src/services/api/learn-detail.ts, src/services/api/types/learn-detail.ts, src/services/mock/learn-detail.data.ts, src/services/mock/learn-detail.ts, src/services/remote/learn-detail.ts
- close #134 
- 메모 부분을 제외하고 반영 완료했습니다.
- 로그인 했을 경우는 getPrivateVideoData, 그렇지 않은 경우는 getPublicVideoData로 데이터를 받아옵니다.
- 학습 상세 페이지에 즐겨찾기 API 연결했습니다.
- 학습 상세 페이지 데이터 잘 받아오는지 확인
https://user-images.githubusercontent.com/58380158/196802413-a948e2e9-4668-4091-8ae0-6e27e68d5d3a.mp4
- 학습 상세 페이지 즐겨찾기 기능 확인
https://user-images.githubusercontent.com/58380158/196868297-6ba89a7a-9a07-49f6-874c-a448f53512ec.mp4
=> [learn_detail] 서버 마이그레이션 반영

package.json, src/pages/_app.tsx, src/utils/constant.ts, src/utils/gtag.ts, yarn.lock
- close #150 
- 웹 로그 분석 툴 GA, Hotjar를 도입했습니다.
- 적용 방법이 궁금하다면 커밋 기록과 함께 이슈에 남겨놓은 링크들을 참고하면 좋을 것 같습니다 😊
특히 Next.js 공식 레포에 GA example code가 친절하게 준비되어 있더라구요
다들 한 번씩 보는 걸 추천합니다 👍🏻
=> [common] GA, Hotjar 도입

src/components/common/NewsList.tsx, src/pages/learn/[id].tsx, src/services/api/learn-detail.ts, src/services/mock/learn-detail.ts, src/services/remote/learn-detail.ts
- close #169 
- 학습 상세 페이지는 반응형이 구현이 안되어 있어서 `similar`라는 타입을 받아서 해당 타입일 경우에는 반응형이 되지 않게 하였습니다.
=> [learn_detail] 비슷한 영상 추천

src/components/common/NavigationBar.tsx, src/components/learnDetail/record/RecordLog.tsx, src/components/learnDetail/record/RecordStatusBar.tsx, src/pages/404.tsx, src/pages/home.tsx, src/pages/learn/[id].tsx, src/pages/learn/index.tsx, src/pages/review.tsx, src/services/remote/login-user.ts
- close #177
- 녹음 다운로드 이름 수정 (보류) -> **cross-origin 문제로 클라에서 다운로드 이름을 수정하지 못 함** + **서버에 저장된 이름은 시간 정보와 관련되어 있어 바꾸지 못 함** 으로 방법을 찾으려면 시간이 걸릴 듯합니다..!
- 녹음 재생바를 자연스럽게 (보류) -> 현재 Audio 객체의 currentTime 기준으로 값을 업데이트하고 있는데요. 이 값이 업데이트되는 주기를 수정할 수 있는지 방법이 있는지 아직 모르겠어서 마찬가지로 시간이 걸릴 듯해요 ㅜ 기획 측에서도 우선순위를 낮게 주었기 때문에 다음 업데이트에 넣어야 할 것 같습니다 
https://user-images.githubusercontent.com/99077953/210210510-271c5c22-4a34-4389-89e1-a92cfc73b024.mov
=> [learn_detail] 1차 QA 반영

src/components/common/Footer.tsx, src/components/common/Like.tsx, src/components/common/NavigationBar.tsx, src/components/common/Pagination.tsx, src/components/common/ProfileModal.tsx, src/components/landing/Header.tsx, src/components/landing/mobileContainer.tsx, src/components/learn/SelectBox.tsx, src/components/learnDetail/ConfirmModal.tsx, src/components/learnDetail/GuideModal.tsx, src/components/learnDetail/HighlightModal.tsx, src/components/learnDetail/ScriptTitle.tsx, src/components/learnDetail/memo/MemoDotButton.tsx, src/components/learnDetail/record/RecordDotButton.tsx, src/components/login/LoginModal.tsx, src/components/review/HeadlineContainer.tsx, src/pages/_document.tsx, src/pages/home.tsx, src/pages/index.tsx, src/pages/learn/[id].tsx, src/pages/review.tsx, src/utils/constant.ts
- close #182 
- 랜딩 페이지는 웹 접근성 점수가 똑같습니다.
이유 : 로티 부분에서 웹 접근성 점수가 낮게 측정됐습니다.
같은 문제를 겪고 있는 경우는 발견했는데, 아직 해결책이 없는 것 같습니다.
>Google Lighthouse reports the aria-label attribute mismatches the element's role.
- 모든 페이지가 `contrast` 때문에 100점을 받지 못했습니다.
명도 대비가 표준에 미치지 않아 저시력자들의 웹 접근성을 지원하기 힘들다고 합니다.
기회가 된다면 디자이너와 논의해서 이런 부분도 개선하면 더 좋을 것 같습니다!
|홈 Before|홈 After|
|:-:|:-:|
|<img src="https://user-images.githubusercontent.com/58380158/216095317-b1805fdc-28f6-49cf-8c6a-651ebf7d5cd5.png" width="300" />|<img src="https://user-images.githubusercontent.com/58380158/216095446-71ea5637-10f2-4ceb-92bf-cf57605dbba2.png" width="300" />|
|학습 상세 Before|학습 상세 After|
|:-:|:-:|
|<img src="https://user-images.githubusercontent.com/58380158/216095568-16644905-445e-4f40-bdbe-bf6b9d7817df.png" width="300" />|<img …
=> [common] 웹 접근성 개선하기

src/components/common/NavigationBar.tsx, src/components/learn/SelectBox.tsx, src/components/learnDetail/ContextMenu.tsx, src/components/learnDetail/ScriptEdit.tsx, src/components/learnDetail/memo/MemoDotButton.tsx, src/components/learnDetail/memo/MemoForm.tsx, src/components/learnDetail/record/RecordDotButton.tsx, src/hooks/useClickOutside.ts, src/pages/learn/[id].tsx
- close #208 
- 여기저기서 사용되던 모달 바깥 클릭시 모달이 닫히는 코드를 커스텀 훅으로 분리하였습니다.
- 외부 클릭시 모달이 닫히도록 하는 코드에 모두 커스텀 훅을 적용하였습니다. 
- 전부 테스트 해보긴 했지만 혹시 동작이 이상한 게 있다면 말씀해주세요.
- 리뷰어의 부담을 줄이기 위해 코드에 대한 코멘트를 달았으니 참고해주시면 감사하겠습니다.
=> [common] 모달 외부 클릭을 제어하는 커스텀 훅 생성

src/components/learnDetail/ScriptTitle.tsx, src/components/learnDetail/VideoDetail.tsx, src/components/learnDetail/scriptEdit/ScriptEdit.tsx, src/hooks/learnDetail/useDeleteElement.ts, src/hooks/learnDetail/useUpdateMemoList.ts, src/pages/learn/[id].tsx, src/pages/learn/index.tsx, src/services/api/learn-detail.ts, src/services/mock/learn-detail.data.ts, src/services/queries/common.ts, src/services/queries/home.ts, src/services/queries/learn-detail.ts, src/services/queries/learn.ts, src/services/remote/base.ts, src/services/remote/learn-detail.ts, src/types/learnDetail/remote.ts
- close #228 
- 코드에 대한 설명은 코멘트로 달겠습니다.
=> [common] 리액트 쿼리 최적화

src/components/learnDetail/record/RecordLog.tsx, src/hooks/learnDetail/useRightClickHandler.ts, src/pages/review.tsx, src/services/remote/learn-detail.ts
=> [common] 자잘한 버그 수정

.eslintrc.json, __mocks__/fileMock.js, __mocks__/styleMock.js, __tests__/learnDetail/ConfirmModal.test.tsx, __tests__/learnDetail/ContextMenu.test.tsx, __tests__/learnDetail/MemoForm.test.tsx, __tests__/learnDetail/memo.test.tsx, jest.config.js, jest.setup.js, package.json, src/components/learnDetail/memo/MemoForm.tsx, src/components/learnDetail/memo/MemoItem.tsx, yarn.lock
- close #236 
- MemoForm 컴포넌트 유닛 테스트 (메모 추가 관련)
- ConfirmModal 컴포넌트 유닛 테스트 (메모 추가 관련)
- ContextMenu 컴포넌트 유닛 테스트
- 리액트 테스팅 라이브러리를 통해서 메모 추가 기능과 관련된 유닛 테스트를 수행하였습니다. 
- 메모 수정과 삭제 관련 유닛 테스트 코드 작성 후 통합 테스트 코드를 작성할 예정입니다.
=> [learn_detail] 메모 추가 기능 관련 유닛 테스트

src/constants/common.ts, src/mocks/api/learnDetail.ts, src/services/remote/base.ts, src/services/remote/common.ts
- close #243 
- 기존 서버 도메인이 만료되어서 새로운 도메인으로 변경하였습니다.
=> [common] 변경된 서버 도메인 반영

next-sitemap.config.js, package.json, public/robots.txt, public/sitemap-0.xml, public/sitemap.xml, yarn.lock
- close #249 
SEO 최적화를 위해 사이트맵을 설정합니다.
=> [common] 사이트맵 설정
